# -*- coding: utf-8 -*-
"""ex7usecase.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y8lNxed9Q23xtV3-1_dV3oa6wjuQDDOg
"""

import numpy as np
from scipy.stats import binom

# Observed data (number of heads out of 10 tosses)
data = np.array([5, 9, 8, 4, 7])
n = 10   # number of tosses per trial

# Initial guesses
theta_A = 0.6
theta_B = 0.5

iterations = 5

print("Initial theta_A =", theta_A)
print("Initial theta_B =", theta_B)
print()

for i in range(iterations):

    # E-Step: calculate responsibility (probability each trial comes from Coin A)
    weights_A = []
    weights_B = []

    for heads in data:
        prob_A = binom.pmf(heads, n, theta_A)
        prob_B = binom.pmf(heads, n, theta_B)

        weight_A = prob_A / (prob_A + prob_B)
        weight_B = prob_B / (prob_A + prob_B)

        weights_A.append(weight_A)
        weights_B.append(weight_B)

    weights_A = np.array(weights_A)
    weights_B = np.array(weights_B)

    # M-Step: update theta values
    theta_A = np.sum(weights_A * data) / (np.sum(weights_A) * n)
    theta_B = np.sum(weights_B * data) / (np.sum(weights_B) * n)

    print(f"Iteration {i+1}:")
    print("theta_A =", round(theta_A, 4))
    print("theta_B =", round(theta_B, 4))
    print()

print("Final Estimated Values:")
print("theta_A =", round(theta_A, 4))
print("theta_B =", round(theta_B, 4))