# -*- coding: utf-8 -*-
"""ex8usecase.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aD--gu7-Rl-lgqlVzZSCAfK4Jz0WA4_X
"""

import math
from collections import Counter

# Training data
students = [
    [2, 30, "Fail"],
    [3, 35, "Fail"],
    [5, 60, "Pass"],
    [6, 65, "Pass"]
]

# Test student
test_student = [4, 50]

# Value of K
k = 3

# Step 1: Calculate Euclidean Distance
distances = []

for student in students:
    distance = math.sqrt(
        (student[0] - test_student[0])**2 +
        (student[1] - test_student[1])**2
    )
    distances.append((distance, student[2]))

# Step 2: Sort by distance
distances.sort()

# Step 3: Get K nearest neighbors
k_neighbors = distances[:k]

# Step 4: Majority Voting
results = [neighbor[1] for neighbor in k_neighbors]
prediction = Counter(results).most_common(1)[0][0]

print("Distances (sorted):")
for d in distances:
    print(d)

print("\nK Nearest Neighbors:")
print(k_neighbors)

print("\nPredicted Result for New Student:", prediction)